### ISSUE TITLE
Agregar formas de instalar al readme

### ISSUE THREAD

**Issue by k3rn3l-st** [atareao/nautilus-pdf-tools#7]
instale nautilus-pdf-tools desde los aur para mi arch que lo toman desde tu github :3 puedes agregar las demas formas de instalar tus extensiones que me gustan mucho :3

**Comment by atareao** [comment]
@k3rn3l-st ¿A que te refieres con agregar las demás forma de instalar? Si me indicas lo añado, claro.

**Comment by luislhl** [comment]
@atareao , maybe one of the additions could be a section about how to install it by cloning the git repo, instead of using the PPA.

You list the prerequisites, but you don't show how to install directly from the repo.

By the way, even with the PPA I wasn't able to install the tool:

```
E: The repository 'https://ppa.launchpadcontent.net/atareao/nautilus-extensions/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package nautilus-pdf-tools
```
